return {
	config=
	{
		[1]=
		{
			id = 1,
			item_id = 1,
			item_key = "cash",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_xj",
			name = "奖金",
			desc = "微信福卡奖金",
		},
		[2]=
		{
			id = 2,
			item_id = 2,
			item_key = "jipaiqi",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jipaiqi",
			is_show_bag = 1,
			order = 2,
			name = "记牌器",
			desc = "记牌器",
		},
		[3]=
		{
			id = 3,
			item_id = 3,
			item_key = "diamond",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_icon_diamond",
			name = "钻石",
			desc = "钻石",
		},
		[4]=
		{
			id = 4,
			item_id = 4,
			item_key = "jing_bi",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jingbi",
			name = "鲸币",
			desc = "鲸币",
		},
		[5]=
		{
			id = 5,
			item_id = 5,
			item_key = "vip",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_btn_close",
			name = "VIP",
			desc = "vip",
		},
		[6]=
		{
			id = 6,
			item_id = 6,
			item_key = "shop_gold_sum",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money",
			name = "福卡",
			desc = "福卡",
		},
		[7]=
		{
			id = 7,
			item_id = 7,
			item_key = "shop_gold_sum_limit",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_moneyed",
			name = "福卡额度",
			desc = "每日福卡额度",
		},
		[8]=
		{
			id = 8,
			item_id = 8,
			item_key = "room_card",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_rc",
			is_show_bag = 1,
			order = 21,
			name = "房卡",
			desc = "创建房卡游戏时使用",
			use_parm = {"roomcard_hall",},
		},
		[9]=
		{
			id = 9,
			item_id = 9,
			item_key = "frame1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz1",
			name = "Lv.10",
			desc = "等级头像框",
		},
		[10]=
		{
			id = 10,
			item_id = 10,
			item_key = "frame2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz2",
			name = "Lv.20",
			desc = "等级头像框",
		},
		[11]=
		{
			id = 11,
			item_id = 11,
			item_key = "frame3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz3",
			name = "Lv.30",
			desc = "等级头像框",
		},
		[12]=
		{
			id = 12,
			item_id = 12,
			item_key = "frame4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz4",
			name = "Lv.40",
			desc = "等级头像框",
		},
		[13]=
		{
			id = 13,
			item_id = 13,
			item_key = "frame5",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz5",
			name = "Lv.50",
			desc = "等级头像框",
		},
		[14]=
		{
			id = 14,
			item_id = 14,
			item_key = "frame6",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz6",
			name = "Lv.60",
			desc = "等级头像框",
		},
		[15]=
		{
			id = 15,
			item_id = 15,
			item_key = "frame7",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz7",
			name = "Lv.70",
			desc = "等级头像框",
		},
		[16]=
		{
			id = 16,
			item_id = 16,
			item_key = "frame8",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz8",
			name = "Lv.80",
			desc = "等级头像框",
		},
		[17]=
		{
			id = 17,
			item_id = 17,
			item_key = "frame9",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz9",
			name = "Lv.90",
			desc = "等级头像框",
		},
		[18]=
		{
			id = 18,
			item_id = 18,
			item_key = "emoticon1",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_water",
			name = "泼水表情",
			desc = "高级互动表情",
		},
		[19]=
		{
			id = 19,
			item_id = 19,
			item_key = "emoticon2",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_guo",
			name = "平底锅表情",
			desc = "高级互动表情",
		},
		[20]=
		{
			id = 20,
			item_id = 20,
			item_key = "emoticon3",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_th",
			name = "戴墨镜表情",
			desc = "高级互动表情",
		},
		[21]=
		{
			id = 21,
			item_id = 21,
			item_key = "emoticon4",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_pig",
			name = "变猪表情",
			desc = "高级互动表情",
		},
		[22]=
		{
			id = 22,
			item_id = 22,
			item_key = "chat",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhk",
			name = "方言特色短语",
			desc = "高级快捷短语",
		},
		[23]=
		{
			id = 23,
			item_id = 23,
			item_key = "broadcast",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_gb",
			name = "登录全服广播",
			desc = "登录时全服播放欢迎广播",
		},
		[24]=
		{
			id = 24,
			item_id = 24,
			item_key = "jipaiqi_free",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jipaiqi",
			name = "免费记牌器",
			desc = "免费使用记牌器",
		},
		[25]=
		{
			id = 25,
			item_id = 101,
			item_key = "match_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_hxs",
			is_show_bag = 0,
			order = -1,
			name = "比赛券",
			desc = "用于参加比赛场的比赛",
		},
		[26]=
		{
			id = 26,
			item_id = 25,
			item_key = "frame10",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz10",
			name = "Lv.100",
			desc = "等级头像框",
		},
		[27]=
		{
			id = 27,
			item_id = 26,
			item_key = "prop_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 0,
			order = 0,
			name = "比赛场门票",
			desc = "可用于参加所有锦标赛",
			use_parm = {"match_hall","hbs",},
		},
		[28]=
		{
			id = 28,
			item_id = 27,
			item_key = "prop_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_qys",
			is_show_bag = 1,
			order = 4,
			name = "千元赛门票",
			desc = "用于报名千元大奖赛",
			use_parm = {"match_hall","gms",},
		},
		[29]=
		{
			id = 29,
			item_id = 28,
			item_key = "real_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 0,
			order = 0,
			name = "黑锅",
			desc = "黑锅",
			real_object = 1,
		},
		[30]=
		{
			id = 30,
			item_id = 29,
			item_key = "prop_hammer_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz1",
			is_show_bag = 1,
			order = 17,
			name = "玩具锤",
			desc = "内部充气的玩具锤，小朋友们的最爱",
			use_parm = {"hall_egg","prop_hammer_1"},
		},
		[31]=
		{
			id = 31,
			item_id = 30,
			item_key = "prop_hammer_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz2",
			is_show_bag = 1,
			order = 18,
			name = "木锤",
			desc = "看起来似乎不太经用的木头锤子",
			use_parm = {"hall_egg","prop_hammer_2"},
		},
		[32]=
		{
			id = 32,
			item_id = 31,
			item_key = "prop_hammer_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz3",
			is_show_bag = 1,
			order = 19,
			name = "银锤",
			desc = "虽然看起来挺像，不过这可不是那把能放电的锤子",
			use_parm = {"hall_egg","prop_hammer_3"},
		},
		[33]=
		{
			id = 33,
			item_id = 32,
			item_key = "prop_hammer_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz4",
			is_show_bag = 1,
			order = 20,
			name = "金锤",
			desc = "听说下雨天金锤和金蛋更配哦！",
			use_parm = {"hall_egg","prop_hammer_4"},
		},
		[34]=
		{
			id = 34,
			item_id = 33,
			item_key = "expression_54",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_666",
			name = "666表情",
			desc = "666表情",
		},
		[35]=
		{
			id = 35,
			item_id = 34,
			item_key = "prop_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_wys",
			is_show_bag = 1,
			order = 3,
			name = "万元赛门票",
			desc = "用于报名万元大奖赛",
			use_parm = {"match_hall","gms",},
		},
		[36]=
		{
			id = 36,
			item_id = 35,
			item_key = "prop_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jyhd",
			is_show_bag = 1,
			order = 5,
			name = "企业赛门票",
			desc = "用于报名企业赛",
			use_parm = {"match_hall","gms",},
		},
		[37]=
		{
			id = 37,
			item_id = 36,
			item_key = "prop_5",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_yys",
			is_show_bag = 1,
			order = 10,
			name = "一元赛门票",
			desc = "用于报名一元赛",
			use_parm = {"match_hall","hbs",},
		},
		[38]=
		{
			id = 38,
			item_id = 37,
			item_key = "fake1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_moneyywy",
			is_show_bag = 0,
			name = "千元第一",
			desc = "第一",
		},
		[39]=
		{
			id = 39,
			item_id = 38,
			item_key = "fake2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money300",
			is_show_bag = 0,
			name = "千元第二",
			desc = "第二",
		},
		[40]=
		{
			id = 40,
			item_id = 39,
			item_key = "fake3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money10000",
			is_show_bag = 0,
			name = "千元第三",
			desc = "第三",
		},
		[41]=
		{
			id = 41,
			item_id = 40,
			item_key = "obj_qianyuansai_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_qys",
			is_show_bag = 1,
			order = 1,
			name = "千元赛门票",
			desc = "千元赛限时门票，限7天内使用！",
			desc_extra = "<size=40><color=#FF0000FF>限时</color><color=#FFF06E>门票，有效时间</color><color=#FF0000FF>7天</color></size>",
			use_parm = {"match_hall","gms",},
		},
		[42]=
		{
			id = 42,
			item_id = 41,
			item_key = "prop_5y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_5ys",
			is_show_bag = 1,
			order = 9,
			name = "五元赛门票",
			desc = "用于报名五元福卡赛",
			use_parm = {"match_hall","hbs",},
		},
		[43]=
		{
			id = 43,
			item_id = 42,
			item_key = "prop_20y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_20ys",
			is_show_bag = 1,
			order = 8,
			name = "二十元赛门票",
			desc = "用于报名二十元福卡赛",
			use_parm = {"match_hall","hbs",},
		},
		[44]=
		{
			id = 44,
			item_id = 43,
			item_key = "prop_100y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100ys",
			is_show_bag = 1,
			order = 6,
			name = "百元赛门票",
			desc = "用于报名一百元福卡赛",
			use_parm = {"match_hall","hbs",},
		},
		[45]=
		{
			id = 45,
			item_id = 44,
			item_key = "prop_50y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50ys",
			is_show_bag = 1,
			order = 7,
			name = "五十元赛门票",
			desc = "用于报名五十元福卡赛",
			use_parm = {"match_hall","hbs",},
		},
		[46]=
		{
			id = 46,
			item_id = 45,
			item_key = "fish_coin",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_icon_yb",
			is_show_bag = 1,
			order = 1,
			name = "捕鱼币",
			desc = "用于捕鱼消耗",
			use_parm = {"game_FishingHall",},
		},
		[47]=
		{
			id = 47,
			item_id = 46,
			item_key = "prop_fish_frozen",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_bd",
			is_show_bag = 1,
			order = 16,
			name = "冰冻",
			desc = "冰冻全场鱼",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[48]=
		{
			id = 48,
			item_id = 47,
			item_key = "prop_fish_lock",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_sd",
			is_show_bag = 1,
			order = 15,
			name = "锁定",
			desc = "锁定攻击鱼",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[49]=
		{
			id = 49,
			item_id = 48,
			item_key = "expression_57",
			lose_time = -1,
			is_local_icon = 1,
			image = "pay_icon_pig",
			name = "猪头表情",
			desc = "猪头表情",
		},
		[50]=
		{
			id = 50,
			item_id = 49,
			item_key = "prop_50hf",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50ys",
			is_show_bag = 1,
			order = 11,
			name = "五十话费赛门票",
			desc = "用于报名50元免费话费赛",
			use_parm = {"match_hall","sws",},
		},
		[51]=
		{
			id = 51,
			item_id = 50,
			item_key = "prop_100hf",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100ys",
			is_show_bag = 1,
			order = 10,
			name = "一百话费赛门票",
			desc = "用于报名100元免费话费赛",
			use_parm = {"match_hall","sws",},
		},
		[52]=
		{
			id = 52,
			item_id = 51,
			item_key = "prop_zongzi",
			lose_time = -1,
			is_local_icon = 1,
			image = "bzdh_icon_5",
			is_show_bag = 0,
			order = 1,
			name = "海盗帽",
			desc = "捕鱼收集粽子赢大奖",
		},
		[53]=
		{
			id = 53,
			item_id = 52,
			item_key = "obj_fish_free_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_danmf2",
			is_show_bag = 1,
			order = 12,
			name = "免费时刻",
			desc = "触发免费时刻",
			use_parm = {"game_FishingHall",},
			tag = 7,
		},
		[54]=
		{
			id = 54,
			item_id = 53,
			item_key = "obj_fish_crit_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_sbsk",
			is_show_bag = 1,
			order = 14,
			name = "双倍时刻",
			desc = "触发双倍时刻",
			use_parm = {"game_FishingHall",},
			tag = 7,
		},
		[55]=
		{
			id = 55,
			item_id = 54,
			item_key = "obj_fish_power_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_cjhl",
			is_show_bag = 1,
			order = 13,
			name = "超级火力",
			desc = "触发超级火力",
			use_parm = {"game_FishingHall",},
			tag = 7,
		},
		[56]=
		{
			id = 56,
			item_id = 55,
			item_key = "prop_6",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_mxyqh",
			is_show_bag = 1,
			order = 6,
			name = "明星大奖赛门票",
			desc = "明星大奖赛门票",
			use_parm = {"match_hall","mxb",},
		},
		[57]=
		{
			id = 57,
			item_id = 56,
			item_key = "obj_fish_super_bomb",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 0,
			name = "超级全屏炸弹",
			desc = "毁天灭地，却无辐射残留",
			tag = 6,
		},
		[58]=
		{
			id = 58,
			item_id = 57,
			item_key = "obj_fish_secondary_bomb",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 2,
			name = "全屏炸弹",
			desc = "再也不用担心炸弹范围太小了",
			tag = 6,
		},
		[59]=
		{
			id = 59,
			item_id = 58,
			item_key = "obj_fish_super_bolt",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dsd",
			is_show_bag = 1,
			order = 1,
			name = "超级全屏闪电",
			desc = "电闪雷鸣，鱼儿无所遁形",
			tag = 6,
		},
		[60]=
		{
			id = 60,
			item_id = 59,
			item_key = "obj_fish_secondary_bolt",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xsd",
			is_show_bag = 1,
			order = 3,
			name = "全屏闪电",
			desc = "让我看看是谁在电鱼！",
			tag = 6,
		},
		[61]=
		{
			id = 61,
			item_id = 60,
			item_key = "obj_fish_lock",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_sd",
			is_show_bag = 1,
			order = 15,
			name = "锁定（比赛专用）",
			desc = "锁定攻击鱼",
			tag = 6,
		},
		[62]=
		{
			id = 62,
			item_id = 61,
			item_key = "prop_fish",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_bybsq",
			is_show_bag = 1,
			order = 1,
			name = "捕鱼比赛券",
			desc = "用于参加捕鱼赛事",
			use_parm = {"game_FishingHall",},
		},
		[63]=
		{
			id = 63,
			item_id = 62,
			item_key = "obj_qys_match_revive_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_fh2",
			is_show_bag = 1,
			order = 21,
			name = "千元赛复活门票",
			desc = "用于千元赛复活",
		},
		[64]=
		{
			id = 64,
			item_id = 63,
			item_key = "prop_7",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_znq",
			is_show_bag = 1,
			order = 22,
			name = "周年感恩赛门票",
			desc = "该门票可用于2019年9月15日20点30分参加周年感恩赛",
			use_parm = {"match_hall","ges"},
		},
		[65]=
		{
			id = 65,
			item_id = 64,
			item_key = "fake4",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp1",
			is_show_bag = 0,
			order = 23,
			name = "10斤长谷子大米",
			desc = "感恩赛奖励",
		},
		[66]=
		{
			id = 66,
			item_id = 65,
			item_key = "fake5",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp4",
			is_show_bag = 0,
			order = 24,
			name = "金条*5g",
			desc = "感恩赛第一名奖励",
		},
		[67]=
		{
			id = 67,
			item_id = 66,
			item_key = "fake6",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp3",
			is_show_bag = 0,
			order = 25,
			name = "金条*2g",
			desc = "感恩赛第二名奖励",
		},
		[68]=
		{
			id = 68,
			item_id = 67,
			item_key = "fake7",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp2",
			is_show_bag = 0,
			order = 26,
			name = "金条*1g",
			desc = "感恩赛第三名奖励",
		},
		[69]=
		{
			id = 69,
			item_id = 68,
			item_key = "obj_fish_match",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_bybsq",
			is_show_bag = 1,
			order = 1,
			name = "捕鱼比赛券（限时）",
			desc = "用于参加捕鱼赛事",
			use_parm = {"game_FishingHall",},
		},
		[70]=
		{
			id = 70,
			item_id = 69,
			item_key = "prop_jinianbi",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_jnb",
			is_show_bag = 1,
			order = 1,
			name = "纪念币",
			desc = "周年活动纪念币",
		},
		[71]=
		{
			id = 71,
			item_id = 70,
			item_key = "prop_znq_dhq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 1,
			order = 1,
			name = "抽奖券",
			desc = "周年庆活动专用",
		},
		[72]=
		{
			id = 72,
			item_id = 71,
			item_key = "obj_fish_drill_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bytx_zt",
			is_show_bag = 1,
			order = 1,
			name = "钻头弹",
			desc = "威力强大的钻头弹，一发惊天动地。可在捕鱼场中使用。",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[73]=
		{
			id = 73,
			item_id = 72,
			item_key = "obj_fish_pierce_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_ctgd",
			is_show_bag = 1,
			order = 1,
			name = "穿透钢弹",
			desc = "可以穿透目标鱼的子弹",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[74]=
		{
			id = 74,
			item_id = 73,
			item_key = "prop_fish_summon_fish",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_shendeng",
			is_show_bag = 1,
			order = 1,
			name = "神灯",
			desc = "擦亮神灯，就会召唤黄金鱼",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[75]=
		{
			id = 75,
			item_id = 74,
			item_key = "sczd_achievement",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cjd",
			is_show_bag = 0,
			order = 1,
			name = "成就点",
			desc = "参与推广活动，获得成就点",
			tag = 2,
		},
		[76]=
		{
			id = 76,
			item_id = 75,
			item_key = "prop_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_jbbx",
			is_show_bag = 1,
			order = -100,
			name = "双11宝箱",
			desc = "宝箱可随机开出1000-15万鲸币。使用时间：2019年11月5日7:30至2019年11月11日23:59:59",
			use_parm = {"open_box",},
		},
		[77]=
		{
			id = 77,
			item_id = 76,
			item_key = "prop_11_cjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq2",
			is_show_bag = 1,
			order = 1,
			name = "双11抽奖券",
			desc = "可在双11抽大奖活动中使用此券进行抽奖。",
		},
		[78]=
		{
			id = 78,
			item_id = 78,
			item_key = "fake8",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift67",
			is_show_bag = 0,
			order = 23,
			name = "敦煌有机红枣",
			desc = "感恩赛奖励",
		},
		[79]=
		{
			id = 79,
			item_id = 79,
			item_key = "prop_xycj_coin",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq3",
			is_show_bag = 1,
			order = 23,
			name = "福利券",
			desc = "用于福卡大转盘的抽奖",
			use_parm = {"xycj","panel",1},
		},
		[80]=
		{
			id = 80,
			item_id = 80,
			item_key = "prop_box_stxt_free",
			lose_time = -1,
			is_local_icon = 1,
			image = "stgc_icon_bx1",
			is_show_bag = 1,
			order = 24,
			name = "免费激励宝箱",
			desc = "师傅给与徒弟的免费激励宝箱可随机开出1000-15万鲸币。",
			use_parm = {"open_box","prop_box_stxt_free"},
			box_id = 4,
		},
		[81]=
		{
			id = 81,
			item_id = 81,
			item_key = "prop_box_stxt_small",
			lose_time = -1,
			is_local_icon = 1,
			image = "stgc_icon_bx2",
			is_show_bag = 1,
			order = 25,
			name = "激励宝箱",
			desc = "师傅给与徒弟的激励宝箱可随机开出1000-15万鲸币。",
			use_parm = {"open_box","prop_box_stxt_small"},
			box_id = 5,
		},
		[82]=
		{
			id = 82,
			item_id = 82,
			item_key = "prop_gns_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 1,
			order = 22,
			name = "华为P40比赛门票",
			desc = "该门票可用户2020年8月29日21点00分参加华为P40比赛",
		},
		[83]=
		{
			id = 83,
			item_id = 83,
			item_key = "fake9",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift91_gm",
			is_show_bag = 0,
			order = 23,
			name = "鹌鹑蛋面条",
			desc = "年末回馈赛奖励",
		},
		[84]=
		{
			id = 84,
			item_id = 84,
			item_key = "prop_new_year_word_kuai",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_1",
			is_show_bag = 1,
			order = 24,
			name = "快",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[85]=
		{
			id = 85,
			item_id = 85,
			item_key = "prop_new_year_word_le",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_2",
			is_show_bag = 1,
			order = 25,
			name = "乐",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[86]=
		{
			id = 86,
			item_id = 86,
			item_key = "prop_new_year_word_xin",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_3",
			is_show_bag = 1,
			order = 26,
			name = "新",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[87]=
		{
			id = 87,
			item_id = 87,
			item_key = "prop_new_year_word_shu",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_4",
			is_show_bag = 1,
			order = 27,
			name = "鼠",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[88]=
		{
			id = 88,
			item_id = 88,
			item_key = "prop_new_year_word_cai",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_5",
			is_show_bag = 1,
			order = 28,
			name = "财",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[89]=
		{
			id = 89,
			item_id = 89,
			item_key = "prop_new_year_word_nian",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_6",
			is_show_bag = 1,
			order = 29,
			name = "年",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[90]=
		{
			id = 90,
			item_id = 90,
			item_key = "prop_new_year_word_yuan",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_7",
			is_show_bag = 1,
			order = 30,
			name = "元",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[91]=
		{
			id = 91,
			item_id = 91,
			item_key = "prop_new_year_word_fa",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_8",
			is_show_bag = 1,
			order = 31,
			name = "發",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[92]=
		{
			id = 92,
			item_id = 92,
			item_key = "prop_new_year_word_dan",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_9",
			is_show_bag = 1,
			order = 32,
			name = "旦",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[93]=
		{
			id = 93,
			item_id = 93,
			item_key = "prop_box_click_like",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_dzyl",
			is_show_bag = 1,
			order = -100,
			name = "点赞宝箱",
			desc = "2020年1月24日-2月8日可开启宝箱，最多可获得10万鲸币。",
			use_parm = {"open_box","prop_box_click_like"},
			box_id = 12,
			beginTime = 1579795200,
			endTime = 1581177599,
		},
		[94]=
		{
			id = 94,
			item_id = 94,
			item_key = "fake10",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift128_xsy",
			is_show_bag = 0,
			order = 33,
			name = "洗手液",
			desc = "月末福利赛预约奖励",
		},
		[95]=
		{
			id = 95,
			item_id = 95,
			item_key = "fake11",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift129_jly",
			is_show_bag = 0,
			order = 34,
			name = "食用油",
			desc = "月末福利赛预约奖励",
		},
		[96]=
		{
			id = 96,
			item_id = 96,
			item_key = "prop_web_chip_huafei",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_hfsp",
			is_show_bag = 1,
			order = 35,
			name = "话费碎片",
			desc = "累计一定数量可以兑换话费",
			use_parm = {"duihuan_shop",},
		},
		[97]=
		{
			id = 97,
			item_id = 97,
			item_key = "prop_fish_secondary_bomb_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 1,
			name = "原子弹-浅水湾",
			desc = "原子弹-浅水湾",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 1,
		},
		[98]=
		{
			id = 98,
			item_id = 98,
			item_key = "prop_fish_super_bomb_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 1,
			name = "超级原子弹-浅水湾",
			desc = "超级原子弹-浅水湾",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 1,
		},
		[99]=
		{
			id = 99,
			item_id = 99,
			item_key = "prop_fish_secondary_bomb_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 1,
			name = "原子弹-深海寻宝",
			desc = "原子弹-深海寻宝",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 2,
		},
		[100]=
		{
			id = 100,
			item_id = 100,
			item_key = "prop_fish_super_bomb_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 1,
			name = "超级原子弹-深海寻宝",
			desc = "超级原子弹-深海寻宝",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 2,
		},
		[101]=
		{
			id = 101,
			item_id = 101,
			item_key = "prop_fish_secondary_bomb_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 1,
			name = "原子弹-地底遗迹",
			desc = "原子弹-地底遗迹",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 3,
		},
		[102]=
		{
			id = 102,
			item_id = 102,
			item_key = "prop_fish_super_bomb_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 1,
			name = "超级原子弹-地底遗迹",
			desc = "超级原子弹-地底遗迹",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 3,
		},
		[103]=
		{
			id = 103,
			item_id = 103,
			item_key = "obj_3d_fish_free_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_1",
			is_show_bag = 1,
			order = 36,
			name = "免费子弹-3D捕鱼",
			desc = "免费子弹-3D捕鱼",
			tag = 8,
		},
		[104]=
		{
			id = 104,
			item_id = 104,
			item_key = "obj_3d_fish_power_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_2",
			is_show_bag = 1,
			order = 37,
			name = "超级火力-3D捕鱼",
			desc = "超级火力-3D捕鱼",
			tag = 8,
		},
		[105]=
		{
			id = 105,
			item_id = 105,
			item_key = "obj_3d_fish_crit_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_3",
			is_show_bag = 1,
			order = 38,
			name = "双倍时刻-3D捕鱼",
			desc = "双倍时刻-3D捕鱼",
			tag = 8,
		},
		[106]=
		{
			id = 106,
			item_id = 106,
			item_key = "obj_3d_fish_quick_shoot",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_4",
			is_show_bag = 1,
			order = 39,
			name = "超速子弹-3D捕鱼",
			desc = "超速子弹-3D捕鱼",
			tag = 8,
		},
		[107]=
		{
			id = 107,
			item_id = 107,
			item_key = "obj_3d_fish_drill_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_icon_zt",
			is_show_bag = 1,
			order = 40,
			name = "钻头弹-3D捕鱼",
			desc = "钻头弹-3D捕鱼",
			tag = 8,
		},
		[108]=
		{
			id = 108,
			item_id = 108,
			item_key = "obj_3d_fish_pierce_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_6",
			is_show_bag = 1,
			order = 41,
			name = "穿透子弹-3D捕鱼",
			desc = "穿透子弹-3D捕鱼",
			tag = 8,
		},
		[109]=
		{
			id = 109,
			item_id = 109,
			item_key = "prop_3d_fish_summon_fish",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_btn_zh",
			is_show_bag = 1,
			order = 42,
			name = "召唤-3D捕鱼",
			desc = "召唤-3D捕鱼",
			tag = 8,
		},
		[110]=
		{
			id = 110,
			item_id = 110,
			item_key = "obj_fish_3d_time_free_power_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_8",
			is_show_bag = 1,
			order = 43,
			name = "免费超级火力-3D捕鱼",
			desc = "免费超级火力-3D捕鱼",
			tag = 8,
		},
		[111]=
		{
			id = 111,
			item_id = 111,
			item_key = "obj_fish_3d_laser_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_icon_jg",
			is_show_bag = 1,
			order = 44,
			name = "激光炮-3D捕鱼",
			desc = "激光炮-3D捕鱼",
			tag = 8,
		},
		[112]=
		{
			id = 112,
			item_id = 112,
			item_key = "fake12",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift136_jlygm",
			is_show_bag = 0,
			order = 34,
			name = "金龙鱼挂面",
			desc = "月末福利赛预约奖励",
		},
		[113]=
		{
			id = 113,
			item_id = 113,
			item_key = "prop_npca_hb",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money",
			is_show_bag = 0,
			order = 35,
			name = "支付宝红包",
			desc = "支付宝红包可提现",
		},
		[114]=
		{
			id = 114,
			item_id = 114,
			item_key = "prop_3d_fish_frozen",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_btn_bd",
			is_show_bag = 1,
			order = 32,
			name = "冰冻-3D捕鱼",
			desc = "冰冻全场鱼-3D捕鱼",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[115]=
		{
			id = 115,
			item_id = 115,
			item_key = "prop_3d_fish_lock",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_btn_sd",
			is_show_bag = 1,
			order = 33,
			name = "锁定-3D捕鱼",
			desc = "锁定攻击鱼-3D捕鱼",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[116]=
		{
			id = 116,
			item_id = 116,
			item_key = "prop_mfcjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "免费抽奖券",
			desc = "免费抽奖券",
		},
		[117]=
		{
			id = 117,
			item_id = 117,
			item_key = "prop_sunshine",
			lose_time = -1,
			is_local_icon = 1,
			image = "xycd_icon_ty",
			is_show_bag = 0,
			order = 33,
			name = "阳光值",
			desc = "阳光值",
		},
		[118]=
		{
			id = 118,
			item_id = 118,
			item_key = "prop_carnation",
			lose_time = -1,
			is_local_icon = 1,
			image = "mqjth_icon_knx",
			is_show_bag = 0,
			order = 34,
			name = "康乃馨",
			desc = "康乃馨",
		},
		[119]=
		{
			id = 119,
			item_id = 119,
			item_key = "prop_shovel",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_chanz1",
			is_show_bag = 0,
			order = 33,
			name = "铲子",
			desc = "铲子",
		},
		[120]=
		{
			id = 120,
			item_id = 120,
			item_key = "fake13",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift152_shrmj",
			is_show_bag = 0,
			order = 34,
			name = "珊瑚绒毛巾",
			desc = "月末福利赛奖励",
		},
		[121]=
		{
			id = 121,
			item_id = 121,
			item_key = "prop_love",
			lose_time = -1,
			is_local_icon = 1,
			image = "lmlh_icon_ax",
			is_show_bag = 0,
			order = 33,
			name = "爱心",
			desc = "爱心",
		},
		[122]=
		{
			id = 122,
			item_id = 122,
			item_key = "prop_hfdhq",
			lose_time = -1,
			is_local_icon = 1,
			image = "bs20hf_icon_hfq",
			is_show_bag = 0,
			order = 35,
			name = "话费券",
			desc = "用于在兑换话费活动中进行话费兑换",
		},
		[123]=
		{
			id = 123,
			item_id = 123,
			item_key = "prop_guess_apple_bet_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_shui",
			is_show_bag = 0,
			order = 36,
			name = "水滴",
			desc = "用于苹果大战种植",
		},
		[124]=
		{
			id = 124,
			item_id = 124,
			item_key = "prop_guess_apple_bet_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_yg",
			is_show_bag = 0,
			order = 37,
			name = "太阳",
			desc = "用于苹果大战种植",
		},
		[125]=
		{
			id = 125,
			item_id = 125,
			item_key = "prop_guess_apple_bet_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_cc",
			is_show_bag = 0,
			order = 38,
			name = "铲子",
			desc = "用于苹果大战种植",
		},
		[126]=
		{
			id = 126,
			item_id = 126,
			item_key = "prop_guess_apple_bet_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_sc",
			is_show_bag = 0,
			order = 39,
			name = "除虫剂",
			desc = "用于苹果大战种植",
		},
		[127]=
		{
			id = 127,
			item_id = 127,
			item_key = "prop_guess_apple_bet_5",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_fl",
			is_show_bag = 0,
			order = 40,
			name = "肥料",
			desc = "用于苹果大战种植",
		},
		[128]=
		{
			id = 128,
			item_id = 128,
			item_key = "fake14",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift166_htgt",
			is_show_bag = 0,
			order = 41,
			name = "黄桃",
			desc = "月末福利赛奖励",
		},
		[129]=
		{
			id = 129,
			item_id = 129,
			item_key = "fake15",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift162_kt",
			is_show_bag = 0,
			order = 42,
			name = "美的空调",
			desc = "月末福利赛奖励",
		},
		[130]=
		{
			id = 130,
			item_id = 130,
			item_key = "fake16",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift167_mddfb",
			is_show_bag = 0,
			order = 43,
			name = "美的电饭锅",
			desc = "月末福利赛奖励",
		},
		[131]=
		{
			id = 131,
			item_id = 131,
			item_key = "fake17",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift153_fs",
			is_show_bag = 0,
			order = 44,
			name = "美的风扇",
			desc = "月末福利赛奖励",
		},
		[132]=
		{
			id = 132,
			item_id = 132,
			item_key = "prop_mfcjq_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "免费抽奖券",
			desc = "免费抽奖券",
		},
		[133]=
		{
			id = 133,
			item_id = 133,
			item_key = "prop_cjlb_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包白银宝箱（V1-V3）",
		},
		[134]=
		{
			id = 134,
			item_id = 134,
			item_key = "prop_cjlb_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包黄金宝箱（V1-V3）",
		},
		[135]=
		{
			id = 135,
			item_id = 135,
			item_key = "prop_cjlb_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包钻石宝箱（V1-V3）",
		},
		[136]=
		{
			id = 136,
			item_id = 136,
			item_key = "prop_cjlb_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包白银宝箱（V4-V7）",
		},
		[137]=
		{
			id = 137,
			item_id = 137,
			item_key = "prop_cjlb_5",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包黄金宝箱（V4-V7）",
		},
		[138]=
		{
			id = 138,
			item_id = 138,
			item_key = "prop_cjlb_6",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包钻石宝箱（V4-V7）",
		},
		[139]=
		{
			id = 139,
			item_id = 139,
			item_key = "prop_cjlb_7",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包白银宝箱（V8-V12）",
		},
		[140]=
		{
			id = 140,
			item_id = 140,
			item_key = "prop_cjlb_8",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包黄金宝箱（V8-V12）",
		},
		[141]=
		{
			id = 141,
			item_id = 141,
			item_key = "prop_cjlb_9",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包钻石宝箱（V8-V12）",
		},
		[142]=
		{
			id = 142,
			item_id = 142,
			item_key = "prop_zongzi_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_icon_jzz",
			is_show_bag = 0,
			order = 33,
			name = "粽子",
			desc = "端午福利任务获得",
		},
		[143]=
		{
			id = 143,
			item_id = 143,
			item_key = "fake18",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift191_xmh",
			is_show_bag = 0,
			order = 41,
			name = "小麻花",
			desc = "美的冰箱品牌赛奖励",
		},
		[144]=
		{
			id = 144,
			item_id = 144,
			item_key = "fake19",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift192_bx",
			is_show_bag = 0,
			order = 42,
			name = "冰箱",
			desc = "美的冰箱品牌赛奖励",
		},
		[145]=
		{
			id = 145,
			item_id = 145,
			item_key = "fake20",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift193_wbl",
			is_show_bag = 0,
			order = 43,
			name = "微波炉",
			desc = "美的冰箱品牌赛奖励",
		},
		[146]=
		{
			id = 146,
			item_id = 146,
			item_key = "fake21",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift194_zzj",
			is_show_bag = 0,
			order = 44,
			name = "榨汁机",
			desc = "美的冰箱品牌赛奖励",
		},
		[147]=
		{
			id = 147,
			item_id = 147,
			item_key = "prop_brass_hammer_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz2",
			is_show_bag = 0,
			order = 33,
			name = "铜锤",
			desc = "欢乐敲金蛋铜锤（V1-V3）",
		},
		[148]=
		{
			id = 148,
			item_id = 148,
			item_key = "prop_silver_hammer_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz3",
			is_show_bag = 0,
			order = 33,
			name = "银锤",
			desc = "欢乐敲金蛋银锤（V1-V3）",
		},
		[149]=
		{
			id = 149,
			item_id = 149,
			item_key = "prop_gold_hammer_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz4",
			is_show_bag = 0,
			order = 33,
			name = "金锤",
			desc = "欢乐敲金蛋金锤（V1-V3）",
		},
		[150]=
		{
			id = 150,
			item_id = 150,
			item_key = "prop_brass_hammer_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz2",
			is_show_bag = 0,
			order = 33,
			name = "铜锤",
			desc = "欢乐敲金蛋铜锤（V4-V7）",
		},
		[151]=
		{
			id = 151,
			item_id = 151,
			item_key = "prop_silver_hammer_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz3",
			is_show_bag = 0,
			order = 33,
			name = "银锤",
			desc = "欢乐敲金蛋银锤（V4-V7）",
		},
		[152]=
		{
			id = 152,
			item_id = 152,
			item_key = "prop_gold_hammer_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz4",
			is_show_bag = 0,
			order = 33,
			name = "金锤",
			desc = "欢乐敲金蛋金锤（V4-V7）",
		},
		[153]=
		{
			id = 153,
			item_id = 153,
			item_key = "prop_brass_hammer_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz2",
			is_show_bag = 0,
			order = 33,
			name = "铜锤",
			desc = "欢乐敲金蛋铜锤（v8-v12)",
		},
		[154]=
		{
			id = 154,
			item_id = 154,
			item_key = "prop_silver_hammer_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz3",
			is_show_bag = 0,
			order = 33,
			name = "银锤",
			desc = "欢乐敲金蛋银锤（v8-v12)",
		},
		[155]=
		{
			id = 155,
			item_id = 155,
			item_key = "prop_gold_hammer_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz4",
			is_show_bag = 0,
			order = 33,
			name = "金锤",
			desc = "欢乐敲金蛋金锤（v8-v12)",
		},
		[156]=
		{
			id = 156,
			item_id = 156,
			item_key = "prop_double_card_brass",
			lose_time = -1,
			is_local_icon = 1,
			image = "sxlb_icon_tk",
			is_show_bag = 0,
			order = 33,
			name = "翻倍铜卡",
			desc = "盛夏礼包购买获得",
		},
		[157]=
		{
			id = 157,
			item_id = 157,
			item_key = "prop_double_card_silver",
			lose_time = -1,
			is_local_icon = 1,
			image = "sxlb_icon_yk",
			is_show_bag = 0,
			order = 33,
			name = "翻倍银卡",
			desc = "盛夏礼包购买获得",
		},
		[158]=
		{
			id = 158,
			item_id = 158,
			item_key = "prop_double_card_gold",
			lose_time = -1,
			is_local_icon = 1,
			image = "sxlb_icon_jk",
			is_show_bag = 0,
			order = 33,
			name = "翻倍金卡",
			desc = "盛夏礼包购买获得",
		},
		[159]=
		{
			id = 159,
			item_id = 159,
			item_key = "fake22",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift200_wz",
			is_show_bag = 0,
			order = 41,
			name = "夏日短袜",
			desc = "美的空调品牌赛奖励",
		},
		[160]=
		{
			id = 160,
			item_id = 160,
			item_key = "prop_grade",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jf",
			is_show_bag = 0,
			order = 33,
			name = "积分",
			desc = "我要赚积分活动获得",
		},
		[161]=
		{
			id = 161,
			item_id = 161,
			item_key = "prop_double_card_ppc",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_fb",
			is_show_bag = 1,
			order = 1,
			name = "翻倍卡",
			desc = "翻倍卡只在斗地主新手场生效（不包含二人斗地主），每次胜利自动使用，结算福卡兑换不享受翻倍。",
		},
		[162]=
		{
			id = 162,
			item_id = 162,
			item_key = "prop_fish_drop_act_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bzdh_icon_1",
			is_show_bag = 0,
			order = 33,
			name = "黑桃",
			desc = "章鱼来袭活动",
		},
		[163]=
		{
			id = 163,
			item_id = 163,
			item_key = "prop_fish_drop_act_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bzdh_icon_2",
			is_show_bag = 0,
			order = 33,
			name = "红桃",
			desc = "章鱼来袭活动",
		},
		[164]=
		{
			id = 164,
			item_id = 164,
			item_key = "prop_fish_drop_act_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bzdh_icon_3",
			is_show_bag = 0,
			order = 33,
			name = "梅花",
			desc = "章鱼来袭活动",
		},
		[165]=
		{
			id = 165,
			item_id = 165,
			item_key = "prop_fish_drop_act_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "bzdh_icon_4",
			is_show_bag = 0,
			order = 33,
			name = "方块",
			desc = "章鱼来袭活动",
		},
		[166]=
		{
			id = 166,
			item_id = 166,
			item_key = "prop_fish_drop_act_0",
			lose_time = -1,
			is_local_icon = 1,
			image = "lmlh_icon_ax",
			is_show_bag = 0,
			order = 33,
			name = "爱心",
			desc = "浪漫七夕活动",
		},
		[167]=
		{
			id = 167,
			item_id = 167,
			item_key = "prop_imperial",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_hg",
			is_show_bag = 0,
			order = 33,
			name = "皇冠",
			desc = "收集领好礼活动累计赢金获得",
		},
		[168]=
		{
			id = 168,
			item_id = 168,
			item_key = "prop_rare_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "ad_76_1",
			is_show_bag = 1,
			order = 1,
			name = "稀有宝箱",
			desc = "周年庆期间开启，最高可得5万金币或5元话费或5元福卡！",
			use_parm = {"open_box_new","prop_rare_box"},
			box_id = 55,
		},
		[169]=
		{
			id = 169,
			item_id = 169,
			item_key = "prop_epic_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "ad_76_2",
			is_show_bag = 1,
			order = 1,
			name = "史诗宝箱",
			desc = "周年庆期间开启，最高可得10万金币或10元话费或10元福卡！",
			use_parm = {"open_box_new","prop_epic_box"},
			box_id = 56,
		},
		[170]=
		{
			id = 170,
			item_id = 170,
			item_key = "prop_legend_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "ad_76_3",
			is_show_bag = 1,
			order = 1,
			name = "传说宝箱",
			desc = "周年庆期间开启，最高可得20万金币或20元话费或20元福卡！",
			use_parm = {"open_box_new","prop_legend_box"},
			box_id = 57,
		},
		[171]=
		{
			id = 171,
			item_id = 171,
			item_key = "fake23",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift213_hwsj",
			is_show_bag = 0,
			order = 33,
			name = "华为手机",
			desc = "华为手机品牌赛预约奖励",
		},
		[172]=
		{
			id = 172,
			item_id = 172,
			item_key = "fake24",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift211_hwpb",
			is_show_bag = 0,
			order = 33,
			name = "华为平板",
			desc = "华为手机品牌赛预约奖励",
		},
		[173]=
		{
			id = 173,
			item_id = 173,
			item_key = "fake25",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift212_hwsh",
			is_show_bag = 0,
			order = 33,
			name = "华为手环",
			desc = "华为手机品牌赛预约奖励",
		},
		[174]=
		{
			id = 174,
			item_id = 174,
			item_key = "fake26",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift214_yg",
			is_show_bag = 0,
			order = 33,
			name = "佳洁士牙膏",
			desc = "华为手机品牌赛预约奖励",
		},
		[175]=
		{
			id = 175,
			item_id = 175,
			item_key = "prop_2year_jinianbi1",
			lose_time = -1,
			is_local_icon = 1,
			image = "yjlqjnb_icon_jnb",
			is_show_bag = 1,
			order = 1,
			name = "纪念币",
			desc = "2周年活动一期纪念币",
		},
		[176]=
		{
			id = 176,
			item_id = 176,
			item_key = "prop_2year_jinianbi2",
			lose_time = -1,
			is_local_icon = 1,
			image = "yjlqjnb_icon_jnb",
			is_show_bag = 1,
			order = 1,
			name = "纪念币",
			desc = "2周年活动二期纪念币",
		},
		[177]=
		{
			id = 177,
			item_id = 177,
			item_key = "prop_2year_jinianbi3",
			lose_time = -1,
			is_local_icon = 1,
			image = "yjlqjnb_icon_jnb",
			is_show_bag = 1,
			order = 1,
			name = "纪念币",
			desc = "2周年活动三期纪念币",
		},
		[178]=
		{
			id = 178,
			item_id = 178,
			item_key = "prop_5_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq1",
			is_show_bag = 1,
			order = 1,
			name = "5元优惠券",
			desc = "充值商城中购买50元档次鲸币时使用，可抵扣5元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[179]=
		{
			id = 179,
			item_id = 179,
			item_key = "prop_10_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq2",
			is_show_bag = 1,
			order = 1,
			name = "10元优惠券",
			desc = "充值商城中购买98元档次鲸币时使用，可抵扣10元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[180]=
		{
			id = 180,
			item_id = 180,
			item_key = "prop_20_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq3",
			is_show_bag = 1,
			order = 1,
			name = "20元优惠券",
			desc = "充值商城中购买198元档次鲸币时使用，可抵扣20元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[181]=
		{
			id = 181,
			item_id = 181,
			item_key = "prop_50_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq4",
			is_show_bag = 1,
			order = 1,
			name = "50元优惠券",
			desc = "充值商城中购买498元档次鲸币时使用，可抵扣50元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[182]=
		{
			id = 182,
			item_id = 182,
			item_key = "prop_100_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq5",
			is_show_bag = 1,
			order = 1,
			name = "100元优惠券",
			desc = "充值商城中购买998元档次鲸币时使用，可抵扣100元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[183]=
		{
			id = 183,
			item_id = 183,
			item_key = "prop_200_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq6",
			is_show_bag = 1,
			order = 1,
			name = "200元优惠券",
			desc = "充值商城中购买2498元档次鲸币时使用，可抵扣200元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[184]=
		{
			id = 184,
			item_id = 184,
			item_key = "prop_2year_zhou",
			lose_time = -1,
			is_local_icon = 1,
			image = "djjzhhl_icon_znqd1",
			is_show_bag = 1,
			order = 1,
			name = "周",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[185]=
		{
			id = 185,
			item_id = 185,
			item_key = "prop_2year_nian",
			lose_time = -1,
			is_local_icon = 1,
			image = "djjzhhl_icon_znqd2",
			is_show_bag = 1,
			order = 1,
			name = "年",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[186]=
		{
			id = 186,
			item_id = 186,
			item_key = "prop_2year_qing",
			lose_time = -1,
			is_local_icon = 1,
			image = "djjzhhl_icon_znqd3",
			is_show_bag = 1,
			order = 1,
			name = "庆",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[187]=
		{
			id = 187,
			item_id = 187,
			item_key = "prop_2year_dian",
			lose_time = -1,
			is_local_icon = 1,
			image = "djjzhhl_icon_znqd4",
			is_show_bag = 1,
			order = 1,
			name = "典",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[188]=
		{
			id = 188,
			item_id = 188,
			item_key = "prop_2year_wan",
			lose_time = -1,
			is_local_icon = 1,
			image = "djjzhhl_icon_znqd5",
			is_show_bag = 1,
			order = 1,
			name = "万",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[189]=
		{
			id = 189,
			item_id = 189,
			item_key = "prop_2year_gift1",
			lose_time = -1,
			is_local_icon = 1,
			image = "eznhk_icon_1",
			is_show_bag = 1,
			order = 1,
			name = "鲸币礼包",
			desc = "最高可获得10万鲸币！",
			use_parm = {"open_box_new","prop_2year_gift1"},
			box_id = 60,
		},
		[190]=
		{
			id = 190,
			item_id = 190,
			item_key = "prop_2year_gift2",
			lose_time = -1,
			is_local_icon = 1,
			image = "eznhk_icon_2",
			is_show_bag = 1,
			order = 1,
			name = "鲸币宝箱",
			desc = "最高可获得50万鲸币！",
			use_parm = {"open_box_new","prop_2year_gift2"},
			box_id = 61,
		},
		[191]=
		{
			id = 191,
			item_id = 191,
			item_key = "prop_2year_gift3",
			lose_time = -1,
			is_local_icon = 1,
			image = "eznhk_icon_3",
			is_show_bag = 1,
			order = 1,
			name = "大额鲸币宝箱",
			desc = "最高可获得200万鲸币！",
			use_parm = {"open_box_new","prop_2year_gift3"},
			box_id = 62,
		},
		[192]=
		{
			id = 192,
			item_id = 192,
			item_key = "prop_2year_gift4",
			lose_time = -1,
			is_local_icon = 1,
			image = "eznhk_icon_4",
			is_show_bag = 1,
			order = 1,
			name = "巨额鲸币宝箱",
			desc = "最高可获得500万鲸币！",
			use_parm = {"open_box_new","prop_2year_gift4"},
			box_id = 63,
		},
		[193]=
		{
			id = 193,
			item_id = 193,
			item_key = "prop_2year_gift5",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift201_dlb",
			is_show_bag = 0,
			order = 1,
			name = "回馈大礼包",
			desc = "回馈大礼包：保温杯，自动雨伞，笔记本和签字笔",
		},
		[194]=
		{
			id = 194,
			item_id = 194,
			item_key = "prop_2year_silvercoin",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift203_jnb",
			is_show_bag = 0,
			order = 1,
			name = "纯银纪念币",
			desc = "纯银纪念币：鲸鱼新家园专属纪念币",
		},
		[195]=
		{
			id = 195,
			item_id = 195,
			item_key = "prop_2year_goldbeads",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift202_zyz",
			is_show_bag = 0,
			order = 1,
			name = "黄金转运珠",
			desc = "黄金转运珠：12生肖黄金转运珠",
		},
		[196]=
		{
			id = 196,
			item_id = 196,
			item_key = "prop_2year_pintu1",
			lose_time = -1,
			is_local_icon = 1,
			image = "djpt_icon_1",
			is_show_bag = 1,
			order = 1,
			name = "图1",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[197]=
		{
			id = 197,
			item_id = 197,
			item_key = "prop_2year_pintu2",
			lose_time = -1,
			is_local_icon = 1,
			image = "djpt_icon_2",
			is_show_bag = 1,
			order = 1,
			name = "图2",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[198]=
		{
			id = 198,
			item_id = 198,
			item_key = "prop_2year_pintu3",
			lose_time = -1,
			is_local_icon = 1,
			image = "djpt_icon_3",
			is_show_bag = 1,
			order = 1,
			name = "图3",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[199]=
		{
			id = 199,
			item_id = 199,
			item_key = "prop_2year_pintu4",
			lose_time = -1,
			is_local_icon = 1,
			image = "djpt_icon_4",
			is_show_bag = 1,
			order = 1,
			name = "图4",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[200]=
		{
			id = 200,
			item_id = 200,
			item_key = "prop_2year_pintu5",
			lose_time = -1,
			is_local_icon = 1,
			image = "djpt_icon_wnt",
			is_show_bag = 1,
			order = 1,
			name = "万能图",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[201]=
		{
			id = 201,
			item_id = 201,
			item_key = "_common_rank_anniversary_celebration_score_rank",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jf",
			is_show_bag = 1,
			order = 1,
			name = "积分",
			desc = "周年庆典，积分达人榜排行标准",
		},
		[202]=
		{
			id = 202,
			item_id = 202,
			item_key = "prop_brass_key_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_6",
			is_show_bag = 0,
			order = 33,
			name = "铜钥匙",
			desc = "欢乐开宝箱铜钥匙",
		},
		[203]=
		{
			id = 203,
			item_id = 203,
			item_key = "prop_silver_key_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_5",
			is_show_bag = 0,
			order = 33,
			name = "银钥匙",
			desc = "欢乐开宝箱银钥匙",
		},
		[204]=
		{
			id = 204,
			item_id = 204,
			item_key = "prop_gold_key_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_4",
			is_show_bag = 0,
			order = 33,
			name = "金钥匙",
			desc = "欢乐开宝箱金钥匙",
		},
		[205]=
		{
			id = 205,
			item_id = 205,
			item_key = "prop_brass_key_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_6",
			is_show_bag = 0,
			order = 33,
			name = "铜钥匙",
			desc = "欢乐开宝箱铜钥匙",
		},
		[206]=
		{
			id = 206,
			item_id = 206,
			item_key = "prop_silver_key_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_5",
			is_show_bag = 0,
			order = 33,
			name = "银钥匙",
			desc = "欢乐开宝箱银钥匙",
		},
		[207]=
		{
			id = 207,
			item_id = 207,
			item_key = "prop_gold_key_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_4",
			is_show_bag = 0,
			order = 33,
			name = "金钥匙",
			desc = "欢乐开宝箱金钥匙",
		},
		[208]=
		{
			id = 208,
			item_id = 208,
			item_key = "prop_brass_key_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_6",
			is_show_bag = 0,
			order = 33,
			name = "铜钥匙",
			desc = "欢乐开宝箱铜钥匙",
		},
		[209]=
		{
			id = 209,
			item_id = 209,
			item_key = "prop_silver_key_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_5",
			is_show_bag = 0,
			order = 33,
			name = "银钥匙",
			desc = "欢乐开宝箱银钥匙",
		},
		[210]=
		{
			id = 210,
			item_id = 210,
			item_key = "prop_gold_key_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_4",
			is_show_bag = 0,
			order = 33,
			name = "金钥匙",
			desc = "欢乐开宝箱金钥匙",
		},
		[211]=
		{
			id = 211,
			item_id = 211,
			item_key = "prop_031_aster",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_icon_xx2",
			is_show_bag = 0,
			order = 33,
			name = "星星",
			desc = "国庆快乐活动获得道具",
		},
		[212]=
		{
			id = 212,
			item_id = 212,
			item_key = "_common_rank_happy_guoqing_aster_rank",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_icon_xx2",
			is_show_bag = 0,
			order = 33,
			name = "积分",
			desc = "国庆快乐活动获得道具",
		},
		[213]=
		{
			id = 213,
			item_id = 213,
			item_key = "prop_new_1y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_1yhf",
			is_show_bag = 1,
			order = 1,
			name = "1福卡赛门票",
			desc = "用于参加1福卡赛",
		},
		[214]=
		{
			id = 214,
			item_id = 214,
			item_key = "prop_new_10y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_10fks",
			is_show_bag = 1,
			order = 1,
			name = "10福卡赛门票",
			desc = "用于参加10福卡赛",
		},
		[215]=
		{
			id = 215,
			item_id = 215,
			item_key = "prop_new_50y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50yhf",
			is_show_bag = 1,
			order = 1,
			name = "50元话费赛门票",
			desc = "用于参加50元话费赛",
		},
		[216]=
		{
			id = 216,
			item_id = 216,
			item_key = "prop_new_100y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100fks",
			is_show_bag = 1,
			order = 1,
			name = "100福卡赛门票",
			desc = "用于参加100元话费赛",
		},
		[217]=
		{
			id = 217,
			item_id = 217,
			item_key = "prop_new_200y_before_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_200jdkys",
			is_show_bag = 1,
			order = 1,
			name = "200元JD卡预赛门票",
			desc = "用于参加200元JD卡预赛",
		},
		[218]=
		{
			id = 218,
			item_id = 218,
			item_key = "prop_new_200y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_200jdkjs",
			is_show_bag = 1,
			order = 1,
			name = "200元JD卡决赛门票",
			desc = "用于参加200元JD卡决赛",
		},
		[219]=
		{
			id = 219,
			item_id = 219,
			item_key = "obj_prop_new_1y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_1yhf",
			is_show_bag = 1,
			order = 1,
			name = "1福卡赛门票",
			desc = "用于参加1福卡赛",
		},
		[220]=
		{
			id = 220,
			item_id = 220,
			item_key = "obj_prop_new_10y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_10fks",
			is_show_bag = 1,
			order = 1,
			name = "10福卡赛门票",
			desc = "用于参加10福卡赛",
		},
		[221]=
		{
			id = 221,
			item_id = 221,
			item_key = "obj_prop_new_50y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50yhf",
			is_show_bag = 1,
			order = 1,
			name = "50元话费赛门票",
			desc = "用于参加50元话费赛",
		},
		[222]=
		{
			id = 222,
			item_id = 222,
			item_key = "obj_prop_new_100y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100fks",
			is_show_bag = 1,
			order = 1,
			name = "100福卡赛门票",
			desc = "用于参加100元话费赛",
		},
		[223]=
		{
			id = 223,
			item_id = 223,
			item_key = "obj_prop_new_200y_before_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_200jdkys",
			is_show_bag = 1,
			order = 1,
			name = "200元JD卡预赛门票",
			desc = "用于参加200元JD卡预赛",
		},
		[224]=
		{
			id = 224,
			item_id = 224,
			item_key = "obj_prop_new_200y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_200jdkjs",
			is_show_bag = 1,
			order = 1,
			name = "200元JD卡决赛门票",
			desc = "用于参加200元JD卡决赛",
		},
	},
}