return {
	config=
	{
		[1]=
		{
			id = 1,
			item_id = 1,
			item_key = "cash",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_btn_close",
			name = "现金",
			desc = "现金",
		},
		[2]=
		{
			id = 2,
			item_id = 2,
			item_key = "jipaiqi",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jipaiqi",
			is_show_bag = 1,
			order = 1,
			name = "记牌器",
			desc = "记牌器",
		},
		[3]=
		{
			id = 3,
			item_id = 3,
			item_key = "diamond",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_icon_diamond",
			name = "钻石",
			desc = "钻石",
		},
		[4]=
		{
			id = 4,
			item_id = 4,
			item_key = "jing_bi",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jingbi",
			name = "鲸币",
			desc = "鲸币",
		},
		[5]=
		{
			id = 5,
			item_id = 5,
			item_key = "vip",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_btn_close",
			name = "VIP",
			desc = "vip",
		},
		[6]=
		{
			id = 6,
			item_id = 6,
			item_key = "shop_gold_sum",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money",
			name = "红包券",
			desc = "红包券",
		},
		[7]=
		{
			id = 7,
			item_id = 7,
			item_key = "shop_gold_sum_limit",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_moneyed",
			name = "红包券额度",
			desc = "每日红包券额度",
		},
		[8]=
		{
			id = 8,
			item_id = 8,
			item_key = "room_card",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_rc",
			is_show_bag = 1,
			order = 2,
			name = "房卡",
			desc = "创建房卡游戏时使用",
		},
		[9]=
		{
			id = 9,
			item_id = 9,
			item_key = "frame1",
			lose_time = -1,
			is_local_icon = 1,
			image = "hall_bg_headk0",
			name = "八品头像框",
			desc = "段位专属头像框",
		},
		[10]=
		{
			id = 10,
			item_id = 10,
			item_key = "frame2",
			lose_time = -1,
			is_local_icon = 1,
			image = "hall_bg_headk7",
			name = "七品头像框",
			desc = "段位专属头像框",
		},
		[11]=
		{
			id = 11,
			item_id = 11,
			item_key = "frame3",
			lose_time = -1,
			is_local_icon = 1,
			image = "hall_bg_headk6",
			name = "六品头像框",
			desc = "段位专属头像框",
		},
		[12]=
		{
			id = 12,
			item_id = 12,
			item_key = "frame4",
			lose_time = -1,
			is_local_icon = 1,
			image = "hall_bg_headk4",
			name = "五品头像框",
			desc = "段位专属头像框",
		},
		[13]=
		{
			id = 13,
			item_id = 13,
			item_key = "frame5",
			lose_time = -1,
			is_local_icon = 1,
			image = "hall_bg_headk14",
			name = "四品头像框",
			desc = "段位专属头像框",
		},
		[14]=
		{
			id = 14,
			item_id = 14,
			item_key = "frame6",
			lose_time = -1,
			is_local_icon = 1,
			image = "hall_bg_headk8",
			name = "三品头像框",
			desc = "段位专属头像框",
		},
		[15]=
		{
			id = 15,
			item_id = 15,
			item_key = "frame7",
			lose_time = -1,
			is_local_icon = 1,
			image = "hall_bg_headk9",
			name = "二品头像框",
			desc = "段位专属头像框",
		},
		[16]=
		{
			id = 16,
			item_id = 16,
			item_key = "frame8",
			lose_time = -1,
			is_local_icon = 1,
			image = "hall_bg_headk2",
			name = "一品头像框",
			desc = "段位专属头像框",
		},
		[17]=
		{
			id = 17,
			item_id = 17,
			item_key = "frame9",
			lose_time = -1,
			is_local_icon = 1,
			image = "hall_bg_headk10",
			name = "皇帝头像框",
			desc = "段位专属头像框",
		},
		[18]=
		{
			id = 18,
			item_id = 18,
			item_key = "emoticon1",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_water",
			name = "泼水表情",
			desc = "高级互动表情",
		},
		[19]=
		{
			id = 19,
			item_id = 19,
			item_key = "emoticon2",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_guo",
			name = "平底锅表情",
			desc = "高级互动表情",
		},
		[20]=
		{
			id = 20,
			item_id = 20,
			item_key = "emoticon3",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_th",
			name = "戴墨镜表情",
			desc = "高级互动表情",
		},
		[21]=
		{
			id = 21,
			item_id = 21,
			item_key = "emoticon4",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_pig",
			name = "变猪表情",
			desc = "高级互动表情",
		},
		[22]=
		{
			id = 22,
			item_id = 22,
			item_key = "chat",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhk",
			name = "方言快捷短语",
			desc = "高级快捷短语",
		},
		[23]=
		{
			id = 23,
			item_id = 23,
			item_key = "broadcast",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_gb",
			name = "登录全服广播",
			desc = "登录时全服播放欢迎广播",
		},
		[24]=
		{
			id = 24,
			item_id = 24,
			item_key = "jipaiqi_free",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jipaiqi",
			name = "免费记牌器",
			desc = "免费使用记牌器",
		},
		[25]=
		{
			id = 25,
			item_id = 101,
			item_key = "match_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_hxs",
			is_show_bag = 1,
			order = -1,
			name = "比赛券",
			desc = "用于参加比赛场的比赛",
		},
	},
}